return multiple separate images
packpackame/computation pull request #1
Opened 2023-01-05 18:08 UTC by AdelZakirov

New method `artist.prepare_results` that returns dict of 3 colorizations + original image. Checked that one, worked well. 
@artemkondyukov pls check `models.py` and `routes.py`

2023-01-11 21:00 UTC, artemkondyukov requested changes

2023-01-11 21:00 UTC, artemkondyukov commented on packpacka-compute/models.py
> +    image_original: str
Может лучше сделаем список?
```
image_original: str
images_colorized: List[str]
```

2023-01-11 21:00 UTC, artemkondyukov commented on packpacka-compute/routes.py
> +    # result_image = artist.visualize(image, prediction, original_size=False, inline=3)
Это нужно?

2023-01-11 21:00 UTC, artemkondyukov commented on packpacka-compute/routes.py
> +        image.save(buffered, format="JPEG")
Тут все сломалось, потому что раньше это был PIL.Image, а теперь numpy.ndarray

2023-01-19 19:52 UTC, AdelZakirov commented on model/inference.py
> +        grayscale_image = cv2.resize(grayscale_image, (width, height))
вот тут я бы не стал так делать, лучше оригинальную картинку заново сделать черно-белой. это скажется на строке 75
смотри какая логика короче:
- оригинальная картинка может быть любого размера, который обычно больше того, что подается в нейронку (256х256), цветной предикт нейронки тоже 256х256
- чтобы привести все к оригинальному разрешению без потерь в разрешении и без шакалов, я делаю финт ушами в resize_colorized
- а именно: я беру оригинальную картинку и делаю ее прям grayscale, чтобы был один канал - это интенсивность aka L, цветной предикт я перевожу из RGB в LAB (L – Lightness/Intensity, a – color component ranging from Green to Magenta, b – color component ranging from Blue to Yellow). Из предикта в LAB я беру только A & B (отвечают за цвет) и ресайзю к L оригинальной картинки и получаю новый LAB без потери разрешения. Смекаешь? Мб ты и так это все знал, но я решил расписать)

2023-02-05 19:25 UTC, merged